name: car_rent_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  flutter_inappwebview: ^5.8.0
  in_app_review: ^2.0.8
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  chip_list: ^2.4.4+8
  firebase_messaging: ^14.2.2
  firebase_core: ^2.21.0
  firebase_remote_config: ^4.3.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/elements/
    - assets/images/settings/
    - assets/images/news/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
        - asset: fonts/SFProDisplay-Light.ttf
        - asset: fonts/SFProDisplay-Medium.ttf
        - asset: fonts/SFProDisplay-Bold.ttf
        - asset: fonts/SFProDisplay-Semibold.ttf
        - asset: fonts/SFProDisplay-Black.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"